//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int cardNumber { get; set; }
        public string keyAccount { get; set; }
        public int typeId { get; set; }
        public decimal moneyCantity { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual cardType cardType { get; set; }
        public virtual user user { get; set; }
    }
}
