//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiDBEntities : DbContext
    {
        public FiDBEntities()
            : base("name=FiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<cardType> cardTypes { get; set; }
        public virtual DbSet<EncryptionKey> EncryptionKeys { get; set; }
        public virtual DbSet<transference> transferences { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
