//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class transference
    {
        public int id { get; set; }
        public int actorId { get; set; }
        public int toUserId { get; set; }
        public decimal cantity { get; set; }
        public System.DateTime transDate { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
